### ISSUE TITLE
where to find the python file which follows 'Algorithm 1 ASGN framework' 

### ISSUE THREAD

**Issue by kimsu55** [HaoZhongkai/AS_Molecule#3]
Thank you for your great work. 
I just wondering where to find the python file which follows 'Algorithm 1 ASGN framework' in your paper. I run 'run_al.py', but it seems to have only one model instead of teacher and student models. If my understanding is wrong, please let me know. Thank you again!!

**Comment by HaoZhongkai** [comment]
Hello,
&nbsp; Thanks for your attention on our work.&nbsp;
&nbsp; The code for complete algorithm1 is in the file wsl_al.py which contains both the student and the teacher model. I will check the readme file carefully and add more detail infomation about the source code.


best,
Zhongkai Hao&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HaoZhongkai/AS_Molecule"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 中午1:31
收件人:&nbsp;"HaoZhongkai/AS_Molecule"<AS_Molecule@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HaoZhongkai/AS_Molecule] where to find the python file which follows 'Algorithm 1 ASGN framework'  (#3)





 
Thank you for your great work.
 I just wondering where to find the python file which follows 'Algorithm 1 ASGN framework' in your paper. I run 'run_al.py', but it seems to have only one model instead of teacher and student models. If my understanding is wrong, please let me know. Thank you again!!
