### ISSUE TITLE
Processed datasets are needed

### ISSUE THREAD

**Issue by momo23333** [HaoZhongkai/AS_Molecule#4]
Thanks for your sharing! And when I reproduce results I found there are so many files in utils/pre, and some wrongs appear:
Traceback (most recent call last):
  File "op_savedata.py", line 67, in <module>
    dataset = MoleDataset(path=path, prop_name='homo', loc=False, glob=True)
  File "/mnt/ls1/seal_pro/AS_Molecule/utils/funcs.py", line 231, in __init__
    self.__get_props()
  File "/mnt/ls1/seal_pro/AS_Molecule/utils/funcs.py", line 249, in __get_props
    self.prop_keys = self.datas[0][4].keys()
AttributeError: 'numpy.ndarray' object has no attribute 'keys'

BTW,I can't find the class MoleDataset2. Could you please release the processed datasets by a download link or something else?

**Comment by HaoZhongkai** [comment]
Hello,
&nbsp; This error occurs because the preprocessing of OPV dataset is wrong. You might first use opvpre_data.py or oppre_data.py to preprocess OPV dataset.
&nbsp; The MoleDataset2 is in file utils/funcs.py.&nbsp;
&nbsp; The files of the processed dataset of OPV is too large. So I recommend you to preprocess the original files of QM9 and OPV on your own computer.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HaoZhongkai/AS_Molecule"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月13日(星期天) 晚上7:51
收件人:&nbsp;"HaoZhongkai/AS_Molecule"<AS_Molecule@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HaoZhongkai/AS_Molecule] Processed datasets are needed (#4)





 
Thanks for your sharing! And when I reproduce results I found there are so many files in utils/pre, and some wrongs appear:
 Traceback (most recent call last):
 File "op_savedata.py", line 67, in 
 dataset = MoleDataset(path=path, prop_name='homo', loc=False, glob=True)
 File "/mnt/ls1/seal_pro/AS_Molecule/utils/funcs.py", line 231, in init
 self.__get_props()
 File "/mnt/ls1/seal_pro/AS_Molecule/utils/funcs.py", line 249, in __get_props
 self.prop_keys = self.datas[0][4].keys()
 AttributeError: 'numpy.ndarray' object has no attribute 'keys'
 
BTW,I can't find the class MoleDataset2. Could you please release the processed datasets by a download link or something else?
